<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>com.alphay.boot</groupId>
    <artifactId>d3code-modules</artifactId>
    <version>${revision}</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>d3code-job</artifactId>

  <description>
    d3code-job 任务调度模块
  </description>

  <dependencies>

    <dependency>
      <groupId>com.alphay.boot</groupId>
      <artifactId>d3code-common-nacos</artifactId>
    </dependency>

    <!-- D3code Common Log -->
    <dependency>
      <groupId>com.alphay.boot</groupId>
      <artifactId>d3code-common-log</artifactId>
    </dependency>

    <dependency>
      <groupId>com.alphay.boot</groupId>
      <artifactId>d3code-common-web</artifactId>
    </dependency>

    <dependency>
      <groupId>com.alphay.boot</groupId>
      <artifactId>d3code-common-dubbo</artifactId>
    </dependency>

    <dependency>
      <groupId>com.alphay.boot</groupId>
      <artifactId>d3code-common-mybatis</artifactId>
    </dependency>

    <dependency>
      <groupId>com.alphay.boot</groupId>
      <artifactId>d3code-common-job</artifactId>
    </dependency>

    <dependency>
      <groupId>com.alphay.boot</groupId>
      <artifactId>d3code-common-tenant</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.alphay.boot</groupId>
          <artifactId>d3code-common-mybatis</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>com.alphay.boot</groupId>
      <artifactId>d3code-common-security</artifactId>
    </dependency>

    <!-- D3code Api System -->
    <dependency>
      <groupId>com.alphay.boot</groupId>
      <artifactId>d3code-api-system</artifactId>
    </dependency>

  </dependencies>

  <build>
    <finalName>${project.artifactId}</finalName>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>${spring-boot.version}</version>
        <configuration>
          <mainClass>com.alphay.boot.job.D3codeJobApplication</mainClass>
          <layout>ZIP</layout>
          <includes>
            <include>
              <groupId>nothing</groupId>
              <artifactId>nothing</artifactId>
            </include>
          </includes>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>target/lib</outputDirectory>
              <excludeTransitive>false</excludeTransitive>
              <stripVersion>false</stripVersion>
              <includeScope>runtime</includeScope>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <parameters>true</parameters>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.1.0</version>
        <configuration>
          <failOnMissingWebXml>false</failOnMissingWebXml>
          <warName>${project.artifactId}</warName>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <skipTests>true</skipTests>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
